version: '3.3'
services:
  web:
    build: .
    ports:
      - "5865:5865"
    env_file:
      - .env
    depends_on:
      - redis
    command: ["--redis-host", "redis", "--redis-port", "6379"]
  # TODO(claudio.wilson): Pin this to a specific image  
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
